// Lab registry for grishchenko.org — edit here; the Lab page renders from this file.
// status: SHIPPED | RUNNING | SHELVED | KILLED.  Each entry: hypothesis → method → result → verdict → cost.
// essay: slug of the essay that tells the full story (optional).
window.LAB_EXPERIMENTS = [
  { id: 'EXP-011', status: 'RUNNING', tag: 'agent', title: 'Personal agent — a team, not an oracle',
    hypothesis: 'A set of role-bound agents around one person raises output without rebuilding the person.',
    method: '‹roles you run: reviewer · planner · researcher · … — and what each is allowed to decide›',
    result: '‹what already works day to day — one concrete example where it covered a weak spot›',
    verdict: 'Open. Blind trust is the failure mode being designed against.',
    cost: '‹hours / week›' },
  { id: 'EXP-010', status: 'RUNNING', tag: 'coach', title: 'Plan linter — detectors 2–5',
    hypothesis: 'The value is not generating a plan; it is catching a bad one. Five classic anti-patterns cover most of it.',
    method: 'Deterministic detectors over a 16-week plan: monotone load · linear ramp with no deload · misplaced peak · bodybuilding split vs competition specificity · training by feel.',
    result: '1 of 5 live (deload cadence, 22 lines). It had zero callers for three months — the spec said "implemented", the code did not.',
    verdict: 'Running. Detector 1 wired into the planner; 2–5 in progress.',
    cost: '3 months of believing a table.', essay: 'linter' },
  { id: 'EXP-009', status: 'RUNNING', tag: 'coach', title: 'Hard holdout v2',
    hypothesis: 'A saturated holdout (80/80) measures nothing. Adversarial tasks will find corpus holes the harness cannot.',
    method: '120 tasks: multi-turn clarification, contradiction bait ("you said the opposite"), pain + fatigue combos, gym slang.',
    result: 'First read found 3 data defects: an unprompted deload, an apology for a contradiction that never happened, one weight not on plates.',
    verdict: 'Running. All three were holes in the corpus, not in the architecture.',
    cost: 'Manual reading. Still the only check that finds these.' },
  { id: 'EXP-008', status: 'SHIPPED', tag: 'coach', title: 'imatrix quantization on my own corpus',
    hypothesis: 'Q4 killed Russian because the quantizer did not know which weights carry it. Task-specific importance stats will.',
    method: 'Run the RU/EN task corpus through the model before compression; collect importance matrix; quantize with it.',
    result: 'Probes 4/8 → 7/8. Hard holdout 41/80 → 71/80. 3.25 GB — Q8 quality at Q4-and-a-bit size. 5.87 bit/weight: shared-KV layers get no stats and are bumped to q6_K.',
    verdict: 'Shipped. Calibration corpus must be your real task, not generic text.',
    cost: 'One evening, after a day of thinking the model was bad.', essay: 'talks' },
  { id: 'EXP-007', status: 'SHELVED', tag: 'coach', title: 'Qwen3 specialists',
    hypothesis: 'Two small specialists beat one generalist: a 0.6B parser and a 1.7B coach.',
    method: 'Same data, same harness, same runtime. Only the template and the registry entry change.',
    result: 'Parser EN 96.3 / RU 92.7 at 640 MB — beats the shipped model on Russian (91.1). Coach 119/120 on the hard holdout vs 108.',
    verdict: 'Shelved by decision: Google models only in the product. Kept as a documented fallback runway.',
    cost: 'A few points of quality and a gigabyte of weight. Licence and explainability are part of the product too.' },
  { id: 'EXP-006', status: 'KILLED', tag: 'coach', title: 'E4B "senior tier" for 8 GB phones',
    hypothesis: 'Devices with 8 GB can carry the bigger model for better answers.',
    method: 'Load E4B on real hardware, not the simulator.',
    result: '~4.6 GB resident memory. The whole phone stalled.',
    verdict: 'Killed. All tiers → E2B. Simulators do not run out of memory the way phones do.',
    cost: 'One tier, one afternoon on hardware.' },
  { id: 'EXP-005', status: 'SHIPPED', tag: 'coach', title: 'One model, three roles',
    hypothesis: 'Parser, coach and clarifier can share weights; the difference lives in the harness, not the model.',
    method: 'Parser: GBNF grammar at decode time, ctx 1024. Coach: free text, ctx 2048, history trimmed in whole turn-pairs. Same Gemma 4 E2B file.',
    result: 'One 3.18 GB download instead of three; one warm backend in memory; no switching.',
    verdict: 'Shipped. Invariant holds: the model is not a source of facts — not one number.',
    cost: 'Two evenings on KV-sharing layers and turn markers (see log).', essay: 'talks' },
  { id: 'EXP-004', status: 'KILLED', tag: 'train', title: 'PyTorch + MPS / CUDA 8 GB for fine-tuning',
    hypothesis: 'The usual stack will train a LoRA on a laptop.',
    method: 'PyTorch on Apple MPS; then unsloth on an 8 GB CUDA card.',
    result: 'MPS: 84 s per iteration and OOM at 42 GB. CUDA: no CPU offload for 4-bit training.',
    verdict: 'Killed. MLX with a bf16 base: ~900–1200 iterations, 90 min on M5/32 GB, peak 17 GB, val-loss 0.105.',
    cost: 'Two dead ends before the working one.' },
  { id: 'EXP-003', status: 'SHIPPED', tag: 'data', title: 'Zero labelled data → 18,642 pairs',
    hypothesis: 'A deterministic generator plus a local teacher replaces annotation entirely.',
    method: 'Swift generator: programmes × athletes × days × question templates, answers rendered by the rules engine. Distillation from a local Gemma 4 26B-A4B for free conversation. Split by programme (33 train / 6 held out), never by pair.',
    result: '24,135 raw → −5,493 duplicates → 18,642 pairs, 50/50 RU/EN, 16 categories. Number gate: 0 rejections.',
    verdict: 'Shipped. API spend for the whole project: 0.',
    cost: 'A generator instead of a labelling budget.', essay: 'talks' },
  { id: 'EXP-002', status: 'SHIPPED', tag: 'sre', title: 'Internal reliability agent',
    hypothesis: 'A recurring class of incidents can be formalized well enough for an agent to act inside a hard boundary.',
    method: 'Boundary first — the class of decision it may make and the line it cannot cross. Model last.',
    result: 'In production. Runs across thousands of internal services. Built alone.',
    verdict: 'Shipped. Details under NDA — the essay is the closest thing to a receipt.',
    cost: '‹›', essay: 'proof' },
  { id: 'EXP-001', status: 'SHIPPED', tag: 'coach', title: 'Periodization engine',
    hypothesis: 'Sixteen weeks of powerlifting prep is a lookup problem, not a formula problem.',
    method: 'Matrix of class × weight category → peak lift count; demographic corrections for age, height, training age. Deterministic Swift, offline, tested.',
    result: 'Green tests. The closed-form version diverged from the matrix; the matrix won.',
    verdict: 'Shipped. The model never touches it — it only phrases what the engine decided.',
    cost: 'My own formulas.' }
];

window.LAB_LOG = [
  { d: '‹date›', tag: 'EXP-010', c: 'mag',  t: 'grep for callers of lintPlan(): 1 — its own test. Three months of "implemented".' },
  { d: '‹date›', tag: 'EXP-009', c: 'cyan', t: 'holdout v2 assembled: 120 tasks. Old set at 80/80 retired — a saturated test measures nothing.' },
  { d: '‹date›', tag: 'EXP-008', c: 'green',t: 'imatrix on own corpus: 41 → 71/80. Q8 quality at 3.25 GB.' },
  { d: '‹date›', tag: 'EXP-008', c: 'mag',  t: 'Q4_K_M: probes 4/8, holdout 41/80. Content fine; Russian collapses into English.' },
  { d: '‹date›', tag: 'EXP-007', c: 'dim',  t: 'Qwen3 pair beats the shipped model. Shelved on vendor policy; runtime kept.' },
  { d: '‹date›', tag: 'EXP-006', c: 'mag',  t: 'E4B on an 8 GB iPhone: 4.6 GB resident, phone stalls. Tier removed.' },
  { d: '‹date›', tag: 'EXP-005', c: 'dim',  t: 'Gemma 4 turn markers are single tokens <|turn> / <turn|>; the old ones tokenize into 7 — prompt echo explained. Two lines of rendering.' },
  { d: '‹date›', tag: 'EXP-005', c: 'dim',  t: 'KV-sharing layers carry no projections; strict loading rejects the checkpoint. Filter the tensors.' },
  { d: '‹date›', tag: 'EXP-004', c: 'green',t: 'MLX: LoRA r=16, bf16 base, 90 min, val-loss 0.105. Quantized base corrupts per-layer embeddings — keep bf16.' },
  { d: '‹date›', tag: 'EXP-004', c: 'mag',  t: 'PyTorch+MPS 84 s/it, OOM at 42 GB. unsloth on 8 GB CUDA: no offload for 4-bit. Both dead.' },
  { d: '‹date›', tag: 'EXP-003', c: 'cyan', t: 'Scorer calibrated on gold answers first: 99.7 / 100 / 100 / 99.4. Instrument before model.' },
  { d: '‹date›', tag: 'EXP-003', c: 'cyan', t: '24,135 raw pairs → 18,642 after dedupe. Split by programme, 33/6.' }
];

// Blameless postmortems for killed / shelved experiments. sev: S1 (product) … S3 (an evening).
window.LAB_POSTMORTEMS = [
  { id: 'PM-004', exp: 'EXP-010', status: 'RESOLVED', sev: 'S1', title: 'Linter marked "implemented" for three months',
    summary: 'The plan linter — the product\'s differentiator — existed as one 22-line check with zero callers from the app. The engine it audits was not wired to the planner either.',
    impact: 'Three months of roadmap built on a feature that did not run. Anti-pattern plans could reach athletes unchecked.',
    root: 'A planning doc contained a status table written in the future tense as if past. The plan was never executed; the table read as a report.',
    trigger: 'Reading the code instead of the doc while preparing a post about the linter.',
    detection: 'grep for callers: exactly one — the function\'s own test.',
    lessons: 'Spec is not code. Plan is not report. Green test is not user. A function with no caller from the product does not exist.',
    actions: 'First check on any "done" feature: grep callers, not tests. Detector 1 wired into the planner. Detectors 2–5 in progress. Two divergent lists of "the five anti-patterns" reconciled into one.' },
  { id: 'PM-003', exp: 'EXP-006', status: 'RESOLVED', sev: 'S2', title: 'E4B tier stalls 8 GB phones',
    summary: 'The larger E4B model, planned as a senior tier for 8 GB devices, made the whole phone unresponsive.',
    impact: 'Tier removed. Every device gets E2B.',
    root: '~4.6 GB resident memory plus the OS working set leaves no headroom; the simulator never showed it.',
    trigger: 'First run on real hardware.',
    detection: 'Manual — the phone froze. No metric was watching resident memory on device.',
    lessons: 'Simulators do not run out of memory the way phones do. Every memory decision is made on hardware.',
    actions: 'Free-memory check before loading weights — honest error instead of an OS kill. 6 GB floor documented; 4 GB devices get the deterministic mode.' },
  { id: 'PM-002', exp: 'EXP-008', status: 'RESOLVED', sev: 'S1', title: 'Q4 quantization silently drops Russian',
    summary: 'Standard Q4_K_M compression kept the content of answers but the model slid into English mid-reply.',
    impact: 'Probes 4/8, hard holdout 41/80. Half the user base unusable.',
    root: 'Generic quantization has no idea which weights carry the second language; it rounds them like any other.',
    trigger: 'Post-merge evaluation of the GGUF on the phone-size quant.',
    detection: 'Language-match rule in the fact scorer — the only automated check that caught it.',
    lessons: 'Calibration data must be your real task, not generic text. Q8 fixes it but 5 GB does not fit a phone.',
    actions: 'imatrix quantization on own RU/EN corpus: 7/8, 71/80 at 3.25 GB. Language match kept as a hard gate.' },
  { id: 'PM-001', exp: 'EXP-004', status: 'RESOLVED', sev: 'S3', title: 'Two training stacks dead before the first useful checkpoint',
    summary: 'PyTorch on Apple MPS ran at 84 s per iteration and went OOM at 42 GB; unsloth on an 8 GB CUDA card had no CPU offload for 4-bit training.',
    impact: 'Two evenings. No model.',
    root: 'Tooling assumptions from cloud GPUs do not hold on a laptop or a small card.',
    trigger: 'First fine-tuning attempt.',
    detection: 'Wall clock and the OOM killer.',
    lessons: 'On Apple hardware, use the native stack. Keep the base in bf16 — a quantized base corrupts per-layer embeddings.',
    actions: 'MLX · LoRA r=16 · ~90 min on M5/32 GB · val-loss 0.105. Recipe documented in the repo.' }
];
